### ISSUE TITLE
whitespace styling doesnt always update

### ISSUE THREAD

**Issue by crazymonkyyy** [orbitalquark/textadept#1]
So I was trying to make the tab arrows grey
```buffer.property['style.whitespace'] = 'fore:$(color.grey)'```
which didn't work instantly, confusing me for a while, I eventually found that it does work, but requires reloading the lexer (dmd in this case)

**Comment by orbitalquark** [comment]
On Mon, 26 Oct 2020 15:30:27 -0700
crazymonkyyy <notifications@github.com> wrote:

> So I was trying to make the tab arrows grey
> ```buffer.property['style.whitespace'] = 'fore:$(color.grey)'```
> which didn't work instantly, confusing me for a while, I eventually found that it does work, but requires reloading the lexer (dmd in this case)

Whitespace styles are a special case. You need to change 'style.dmd_whitespace' instead of 'style.whitespace'. I've updated the documentation to reflect this.

https://github.com/orbitalquark/textadept/commit/9809b072113fa6c39c65e323c5cb1bd2149fa46c
