### ISSUE TITLE
Textadept on Windows fails to display Unicode symbols

### ISSUE THREAD

**Issue by smartmic** [orbitalquark/textadept#233]
My fresh installation of Textadept 11.3 on Windows 10 fails to display many Unicode symbols. I am using the Win32 download release. Opening the same file in e.g. Notepad with the same font displays everything correctly though. 

This is the only entry in init.lua I have:
```lua
if not CURSES then
  view:set_theme('light', {font = 'Hack', size = 14})
end
```

See here in comparison for an Xcompose example with APL symbols, selected encoding in textadept is UTF-8:
![image](https://user-images.githubusercontent.com/6379140/178743658-c4e61572-8daa-42c9-94aa-00b63c4fc52f.png)

Any idea how to fix this?

**Comment by orbitalquark** [comment]
First, some background: GTK is the cross-platform GUI toolkit that Textadept uses. GTK's font rendering is provided by a library called Pango.

The only idea that comes to mind is that Pango cannot read your font's unicode glyphs, either because your font provides them in a way Pango does not understand, or your font is simply unsupported for whatever reason. Maybe see if another "popular" font works. (Popular is subjective. I'm thinking of a widely used font with good unicode support like Liberation, Bitstream Vera, DejaVu, etc.)

I'm afraid this is outside my area of expertise :(

**Comment by smartmic** [comment]
Thanks, that was the right hint. I installed DejaVu font and now the Unicode symbols are shown correctly.
