### ISSUE TITLE
`buffer.upper_case()` with iota subscript adds extra uppercase iota character

### ISSUE THREAD

**Issue by ousia** [orbitalquark/textadept#263]
`buffer.upper_case()` converts the following chars:

```
ᾳῃῳ
ᾀᾁᾂᾃᾄᾅᾆᾇ
ᾀᾁᾂᾃᾄᾅᾆᾇ
ᾐᾑᾒᾓᾔᾕᾖᾗ
ᾠᾡᾢᾣᾤᾥᾦᾧ
```

adding an uppercase iota as extra character:

```
ΑΙΗΙΩΙ
ἈΙἉΙἊΙἋΙἌΙἍΙἎΙἏΙ
ἈΙἉΙἊΙἋΙἌΙἍΙἎΙἏΙ
ἨΙἩΙἪΙἫΙἬΙἭΙἮΙἯΙ
ὨΙὩΙὪΙὫΙὬΙὭΙὮΙὯΙ
```

instead of their precomposed versions:

```
ᾼῌῼ
ᾈᾉᾊᾋᾌᾍᾎᾏ
ᾘᾙᾚᾛᾜᾝᾞᾟ
ᾨᾩᾪᾫᾬᾭᾮᾯ
 ```

The lowercase letters contain subscript iotas, which should be turned into adscript iotas when in uppercase (this is what υπογεγραμμένη and προσγεγραμμένη mean in Greek [https://en.wikipedia.org/wiki/Greek_diacritics#adscript]).

At least, decomposing the adscript iota in an extra uppercase iota character when changing to uppercase generates a string that cannot be converted back with `buffer.lower_case()`.

How can the issue be fixed?

Many thanks for your help.

**Comment by orbitalquark** [comment]
Textadept leverages Scintilla's SCI_UPPERCASE and SCI_LOWERCASE messages[1] for converting between cases. In order to get this fixed, it would be best to either ask on the scintilla-interest mailing list[2] or file a bug on the Scintilla tracker[3].

[1]: https://scintilla.org/ScintillaDoc.html#KeyboardCommands
[2]: https://groups.google.com/group/scintilla-interest
[3]: https://sourceforge.net/p/scintilla/bugs/

**Comment by ousia** [comment]
Thanks to the explanation in https://sourceforge.net/p/scintilla/bugs/2351/, it seems that Unicode is tricky here.

With very few characters there seems to be lowercase version and [titlecase](https://unicode.org/faq/casemap_charprop.html#4).

There is no uppercase, since it seems to require expansion with an extra iota.

**Comment by ousia** [comment]
Sorry, I forgot, closing the issue myself.
