### ISSUE TITLE
Problems with clipboard in 11.4 in Arch Linux

### ISSUE THREAD

**Issue by LevKats** [orbitalquark/textadept#299]
Hi,

I can't copy text from textadept to other windows in 11.4 version (gtk3). It works only in opposite direction when i past something into textadept buffer. Also i can copy/paste inside/between buffers.

I don't use aur package, I compile with:
`
make GTK3=1 deps

make GTK3=1
`
If it is important I run it in Gnome/Wayland.

**Comment by orbitalquark** [comment]
Thanks for the report, but I'm afraid there isn't anything I can do about this. I downloaded and ran the binary from GitHub and do not see this issue on my Ubuntu box. I don't have access to Arch.

**Comment by LevKats** [comment]
Interestingly I can reproduce this issue in scite. Probably this bug https://sourceforge.net/p/scintilla/bugs/2361/ is somehow related.

**Comment by orbitalquark** [comment]
Thanks for digging into this. I think you're right.

**Comment by LevKats** [comment]
It was fixed by gtk3.24.36 update.

**Comment by Selorax** [comment]
@orbitalquark 
Hi. I have a copy-paste issue, but I don't know if that's an instance of this bug or not, I have gtk+ 3.24.31 installed.
Copy and paste with ^V ^C works both ways, middle click paste from other app to TextAdept works fine, if I select something in TextAdept and click middle mouse button in other program, it also works, however,

If I first select something in TextAdept tab, then switch to other tab in it, then I cannot paste with middle click neither in TextAdept, nor to other app, however if I switch back to the tab I selected text in, then I can middle-click paste it again.

Also when I paste text from the same tab, it can only be pasted once, after it has been pasted, selection is dropped and buffer is cleared, which also shouldn't happen.

So, I guess, the main problem is that text buffer is lost when its source is deselected.

**Comment by orbitalquark** [comment]
May I ask you to try this same sort of thing in SciTE? It's another 
Scintilla-based editor that uses GTK. If the same type of issue occurs 
in SciTE, then it is an issue with Scintilla. If you cannot reproduce 
this with SciTE, then it's an issue with Textadept.

**Comment by Selorax** [comment]
@orbitalquark, I have tried installing SciTE on a different computer and there copy-pasting between tabs works fine.

**Comment by orbitalquark** [comment]
I can reproduce what you describe in the GTK version of Textadept, but 
not in the upcoming Qt version. Therefore this is either a GTK issue, or 
a Scintilla on GTK issue. It does not appear to be a Textadept issue. It 
may very well be an instance of OP's bug.

The fact that copy-pasting with SciTE on a different computer does not 
help because it should be the same system as Textadept in order to 
troubleshoot the problem.

**Comment by paaguti** [comment]
Speaking about clipboard, I sometimes see messages about entre clipboard being too old in my QT Tectadept on Linux. Not on Mac or Windows…Enviado desde mi iPhoneEl 14 feb 2023, a las 21:13, orbitalquark ***@***.***> escribió:﻿
I can reproduce what you describe in the GTK version of Textadept, but 
not in the upcoming Qt version. Therefore this is either a GTK issue, or 
a Scintilla on GTK issue. It does not appear to be a Textadept issue. It 
may very well be an instance of OP's bug.

The fact that copy-pasting with SciTE on a different computer does not 
help because it should be the same system as Textadept in order to 
troubleshoot the problem.

**Comment by orbitalquark** [comment]
Please open a new issue or discussion. This issue has been resolved.
