### ISSUE TITLE
No Flatpak for textadept

### ISSUE THREAD

**Issue by EugeneUvin** [orbitalquark/textadept#412]
I was searching for any packaged version, ideally Flatpak to get the latest version, and it looks like the only way to install is to unpack the app to a directory. Is this an intentional decision to only provide this way of installation, or is Flatpak planned for future?

**Comment by orbitalquark** [comment]
I have no plans to release Flatpaks or Snaps.

**Comment by rgieseke** [comment]
I think it's quite common that software is packaged by maintainers external to the core developers. 

See for example here for a few distributions: https://repology.org/project/textadept/versions

(Flatpak not there yet.)

**Comment by orbitalquark** [comment]
I'm going to close this, since I do not have any plans to release Flatpaks or Snaps. It's too much work for me.

Textadept's GitHub Actions are available for anyone to experiment building Flatpaks or Snaps with. I may consider accepting a workflow produced by someone that takes the burden off of me.
