### ISSUE TITLE
Horizontal scrolling in textadept-curses

### ISSUE THREAD

**Issue by jk411** [orbitalquark/textadept#469]
Textadept-curses
With virtual space enabled in
init.ini:

buffer.virtual_space_options = buffer.VS_RECTANGULARSELECTION | buffer.VS_USERACCESSIBLE

- cursor still cannot be placed outside text,
- with a bit of patience if "arrow right" is being held long enough screen scrolls right (cursor stays on eol all the time)

**Comment by orbitalquark** [comment]
Thanks for the report. It looks like the caret does go into virtual space internally, but it is not drawn correctly. I'll look into this when I have a chance.

**Comment by orbitalquark** [comment]
Fixed in Scinterm: https://github.com/orbitalquark/scinterm/commit/8fef14e7ef43082ea84cc0f4f675d38f9ae80b87

Also fixed Textadept's column number reporting when inside virtual space here: https://github.com/orbitalquark/textadept/commit/43ff005bec87392ab6560b983488e43e54e3f36a and here: https://github.com/orbitalquark/textadept/commit/767e18e788a890649f763ac2000fa82e4c258841

These changes should be in the next nightly build.
